export namespace CssStyleConst {
    export const TEXT_METRICS_KEYS = [
        "font-family",
        "font-size",
        "font-style",
        "font-weight",
        "letter-spacing",
        "line-height",
        "text-transform",
        "word-spacing",
    ] as const;

    export const TEXT_RENDERING_KEYS = [
        "background",
        "background-attachment",
        "background-blend-mode",
        "background-clip",
        "background-color",
        "background-image",
        "background-origin",
        "background-position",
        "background-repeat",
        "background-size",
        "border",
        "border-block",
        "border-block-color",
        "border-block-end",
        "border-block-end-color",
        "border-block-end-style",
        "border-block-end-width",
        "border-block-start",
        "border-block-start-color",
        "border-block-start-style",
        "border-block-start-width",
        "border-block-style",
        "border-block-width",
        "border-bottom",
        "border-bottom-color",
        "border-bottom-left-radius",
        "border-bottom-right-radius",
        "border-bottom-style",
        "border-bottom-width",
        "border-color",
        "border-inline",
        "border-inline-color",
        "border-inline-end",
        "border-inline-end-color",
        "border-inline-end-style",
        "border-inline-end-width",
        "border-inline-start",
        "border-inline-start-color",
        "border-inline-start-style",
        "border-inline-start-width",
        "border-inline-style",
        "border-inline-width",
        "border-left",
        "border-left-color",
        "border-left-style",
        "border-left-width",
        "border-radius",
        "border-right",
        "border-right-color",
        "border-right-style",
        "border-right-width",
        "border-style",
        "border-top",
        "border-top-color",
        "border-top-left-radius",
        "border-top-right-radius",
        "border-top-style",
        "border-top-width",
        "border-width",
        "box-decoration-break",
        "box-shadow",
        "color",
        "direction",
        "filter",
        "font",
        "font-feature-settings",
        "font-kerning",
        "font-language-override",
        "font-optical-sizing",
        "font-palette",
        "font-size-adjust",
        "font-stretch",
        "font-synthesis",
        "font-synthesis-position",
        "font-synthesis-small-caps",
        "font-synthesis-style",
        "font-synthesis-weight",
        "font-variant",
        "font-variant-alternates",
        "font-variant-caps",
        "font-variant-east-asian",
        "font-variant-emoji",
        "font-variant-ligatures",
        "font-variant-numeric",
        "font-variant-position",
        "hyphenate-character",
        "hyphenate-limit-chars",
        "hyphens",
        "margin",
        "margin-inline",
        "margin-inline-end",
        "margin-inline-start",
        "mix-blend-mode",
        "opacity",
        "outline",
        "outline-color",
        "outline-offset",
        "outline-style",
        "outline-width",
        "padding",
        "padding-inline",
        "padding-inline-end",
        "padding-inline-start",
        "paint-order",
        "tab-size",
        "text-align",
        "text-align-last",
        "text-combine-upright",
        "text-decoration",
        "text-decoration-color",
        "text-decoration-line",
        "text-decoration-skip-ink",
        "text-decoration-style",
        "text-decoration-thickness",
        "text-emphasis",
        "text-emphasis-color",
        "text-emphasis-position",
        "text-emphasis-style",
        "text-indent",
        "text-justify",
        "text-orientation",
        "text-rendering",
        "text-shadow",
        "text-size-adjust",
        "text-underline-offset",
        "text-underline-position",
        "text-wrap",
        "text-wrap-mode",
        "text-wrap-style",
        "transform",
        "transform-box",
        "transform-origin",
        "translate",
        "unicode-bidi",
        "vertical-align",
        "visibility",
        "white-space",
        "white-space-collapse",
        "word-break",
        "word-wrap",
        "writing-mode",
    ] as const;

    export const INHERITED_CSS_KEYS = [
        "color",
        "cursor",
        "direction",
        "font-variant",
        "letter-spacing",
        "list-style-image",
        "list-style-position",
        "list-style-type",
        "quotes",
        "tab-size",
        "text-align",
        "text-combine-upright",
        "text-indent",
        "text-orientation",
        "text-shadow",
        "visibility",
        "white-space",
        "word-spacing",
        "writing-mode",
    ] as const;

    export const INLINE_EXCLUDED_CSS_KEYS = [
        "align-content",
        "align-items",
        "align-self",
        "block-size",
        "bottom",
        "clear",
        "col-gap",
        "column-count",
        "column-fill",
        "column-gap",
        "column-rule",
        "column-rule-color",
        "column-rule-style",
        "column-rule-width",
        "column-span",
        "column-width",
        "columns",
        "flex",
        "flex-basis",
        "flex-direction",
        "flex-flow",
        "flex-grow",
        "flex-shrink",
        "flex-wrap",
        "grid-area",
        "grid-auto-columns",
        "grid-auto-flow",
        "grid-auto-rows",
        "grid-column-start",
        "grid-column-end",
        "grid-row-start",
        "grid-row-end",
        "grid-template",
        "grid-template-areas",
        "grid-template-columns",
        "grid-template-rows",
        "height",
        "inline-size",
        "inset-block-end",
        "inset-block-start",
        "inset-inline-end",
        "inset-inline-start",
        "justify-content",
        "justify-items",
        "justify-self",
        "left",
        "margin-block-end",
        "margin-block-start",
        "margin-bottom",
        "margin-top",
        "max-block-size",
        "max-height",
        "max-inline-size",
        "max-width",
        "min-block-size",
        "min-height",
        "min-inline-size",
        "min-width",
        "order",
        "place-self",
        "position-anchor",
        "right",
        "row-gap",
        "top",
        "width",
        "z-index",
    ] as const;

    export const CANVAS_TEXT_METRICS_EXCLUDED_CSS_KEYS = [
        "font-feature-settings",
        "font-language-override",
        "font-variant",
        "font-variant-alternates",
        "font-variant-caps",
        "font-variant-east-asian",
        "font-variant-ligatures",
        "font-variant-numeric",
        "font-variant-position",
        "hyphens",
        "line-break",
        "line-height",
        "overflow-wrap",
        "tab-size",
        "text-autospace",
        "text-combine-upright",
        "text-indent",
        "text-justify",
        "text-overflow",
        "text-rendering",
        "text-spacing-trim",
        "text-transform",
        "white-space",
        "word-break",
        "writing-mode",
    ] as const;
}

export namespace CssStyleUtils {
    const TEXT_METRICS_KEY_SET = new Set(CssStyleConst.TEXT_METRICS_KEYS);
    const TEXT_RENDERING_KEY_SET = new Set(CssStyleConst.TEXT_RENDERING_KEYS);
    const INHERITED_CSS_KEY_SET = new Set(CssStyleConst.INHERITED_CSS_KEYS);
    const INLINE_EXCLUDED_CSS_KEY_SET = new Set(CssStyleConst.INLINE_EXCLUDED_CSS_KEYS);
    const CANVAS_TEXT_METRICS_EXCLUDED_CSS_KEY_SET = new Set(CssStyleConst.CANVAS_TEXT_METRICS_EXCLUDED_CSS_KEYS);

    export const isTextMetricsKey = (key: string): key is (typeof CssStyleConst.TEXT_METRICS_KEYS)[number] =>
        TEXT_METRICS_KEY_SET.has(key as any);

    export const isTextRenderingKey = (key: string): key is (typeof CssStyleConst.TEXT_RENDERING_KEYS)[number] =>
        TEXT_RENDERING_KEY_SET.has(key as any);

    export const isInheritedCssKey = (key: string): key is (typeof CssStyleConst.INHERITED_CSS_KEYS)[number] =>
        INHERITED_CSS_KEY_SET.has(key as any);

    export const isInlineExcludedCssKey = (
        key: string,
    ): key is (typeof CssStyleConst.INLINE_EXCLUDED_CSS_KEYS)[number] => INLINE_EXCLUDED_CSS_KEY_SET.has(key as any);

    export const isCanvasTextMetricsExcludedCssKey = (
        key: string,
    ): key is (typeof CssStyleConst.CANVAS_TEXT_METRICS_EXCLUDED_CSS_KEYS)[number] =>
        CANVAS_TEXT_METRICS_EXCLUDED_CSS_KEY_SET.has(key as any);

    export const isBlockLike = (display?: string) =>
        display === "block" ||
        display === "flex" ||
        display === "grid" ||
        display === "table" ||
        display === "list-item";
}
